language: c
os:
  - linux
compiler:
  - clang
matrix:
  include:
    - os: linux
      compiler: musl-gcc
      addons:
        apt:
          packages:
            - musl
            - musl-dev
            - musl-tools
    - language: node_js
      node_js: "node"
      sudo: required
      services: ["docker"]
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make randombytes_test.js
        - make check-js
    - language: node_js
      node_js: "lts/*"
      sudo: required
      services: ["docker"]
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
        - docker exec -it emscripten make randombytes_test.js
        - make check-js
    - os: osx
      language: c
      osx_image: xcode10.1
      compiler: gcc
      addons:
        homebrew:
          packages:
            - gcc@8
    - os: osx
      language: c
      osx_image: xcode10.1
      compiler: clang

script:
  - make
  - make check
